### ISSUE TITLE
Tarhutie Leklerk is invisible

### ISSUE THREAD

**Issue by Lazasar** [jdsmith2816/emw#1]
**Describe the bug**
The alchemist in the first town (Rivervale) is invisible. But you can talk to her... a disable and then enabled solved it

**To Reproduce**

2. Do '...'

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug. If your bug is location based, use the book from [Where in Special Edition am I](https://www.nexusmods.com/skyrimspecialedition/mods/30907) mod.

**Modlist version**

**Did you add any additional mods?**

**Comment by jdsmith2816** [comment]
I'm unable to reproduce this over several attempts.

**Comment by tslaton** [comment]
I'm seeing this issue as well in 1.0.9. Although she was visible the first time I met her, I came back to Riverville after reaching Ark, and she has been invisible ever since.

Don't know if it's related, but I also just noticed there are floating items in the Marketplace house, as if they are on invisible furniture. I haven't noticed anything else odd.

**Comment by tslaton** [comment]
...and now she's back, despite my not having done anything in particular to fix her.

**Comment by jdsmith2816** [comment]
Floating items are due to 'cluttering' of the environment to make it look better but with the assumption that you've already purchased the upgrades.  This is a pretty common practice for vanilla home altering mods but realistically they should be slaving the clutter to the hidden displays so it doesn't look strange in the interim...

Long story short... buy the upgrades and things will no longer be floating.

**Comment by kratores85** [comment]
I had this problem, too. First she was visible, after returning from "Old Tunnel" nearby (for Disenchanted Quest) she was invisible. I spawned her in per console and enabled her. That fixed it for me.

**Comment by jdsmith2816** [comment]
This is no longer an issue for the upcoming release.
