### ISSUE TITLE
Displays in basement of the Marketplace house don't work properly

### ISSUE THREAD

**Issue by Lazasar** [jdsmith2816/emw#38]
For example, Vagran't Ode gets taken out of inventory but doesn't show up

The bell hammer shows up in another display.

Other things like Helm of Inner frost show up properly

**Comment by jdsmith2816** [comment]
This should be fixed in 1.0.3;  the housing mod was updated specifically to fix various display related bugs.  Can you verify if you still have issues and re-open if so?  I haven't unlocked the house yet but if you tell me it's still not fixed then I'll go ahead and make a separate test character to do so and get them working.

**Comment by Lazasar** [comment]
The faction Diplsays may have been fixed by Mod AUthor (Don't know, don't have any) but the weapons are still bugged
