### ISSUE TITLE
NPC Armor set fix needed

### ISSUE THREAD

**Issue by Kosake77** [jdsmith2816/emw#55]
**Describe the bug**
torso + leg = mismatch

**Screenshots**
![20200609215830_1](https://user-images.githubusercontent.com/65853467/84194988-1c9fa280-aa9e-11ea-914f-73fa787d0b61.jpg)

**Modlist version**
1.0.3
**Did you add any additional mods?**
no

**Comment by jdsmith2816** [comment]
That's actually the vanilla enderal set mix; aeterna boots/helmet with that tunic.  Unfortunately most of the NPCs that do set mixing like that look a bit strange due to the new assets...  It'd be great if someone went through the 20 or so NPCs that do this and came up with new outfit mixes for them that look good.

**Comment by jdsmith2816** [comment]
This is no longer an issue for the upcoming release.
